### ISSUE TITLE
[Feature request] Support Linux TTY (Virtual Console) with TMUX

### ISSUE THREAD

**Issue by davidsierradz** [kutsan/zsh-system-clipboard#42] opened 2022-08-29 04:36 UTC
Hi! When loading the plugin inside a TTY, this appears:
```
ERROR  zsh-system-clipboard: Could not find any available clipboard manager. Make sure you have wl-clipboard, xclip, or xsel installed.

ERROR  zsh-system-clipboard: Note that if wl-clipboard is installed and $DISPLAY is set, it won't be used. To override this behavior, set in your environment ZSH_SYSTEM_CLIPBOARD_USE_WL_CLIPBOARD
```
This is a server without `xclip` or `xsel` installed.

Could we allow using the plugin inside a TTY with TMUX and  `ZSH_SYSTEM_CLIPBOARD_TMUX_SUPPORT=true`?

There is another bug, worth mentioning: If you use any binding like `bindkey -M vicmd Y zsh-system-clipboard-vicmd-vi-yank-eol` inside a TTY from a Linux system with `xclip` installed, this error appears:
```
_zsh_highlight_call_widget:2: zsh-system-clipboard-vicmd-vi-yank-eol: function definition file not found
```
Should we check in https://github.com/kutsan/zsh-system-clipboard/blob/master/zsh-system-clipboard.zsh#L63 that not only `xclip` is installed but also that we are in a GUI session (`$DISPLAY`)?
Thanks!

**Comment by doronbehar** [comment] 2022-08-29 07:39
> Could we allow using the plugin inside a TTY with TMUX and `ZSH_SYSTEM_CLIPBOARD_TMUX_SUPPORT=true`?

Of course! This was the intended behavior, but it got slipped away during testing of this feature.

In general, I think we need to rewrite most of that logic, it's a mess. I'm working on that now @kutsan.

> _zsh_highlight_call_widget:2: zsh-system-clipboard-vicmd-vi-yank-eol: function definition file not

I really don't know what this error means. Perhaps after a rewrite it'll be fixed..

**Comment by doronbehar** [comment] 2022-08-29 21:26
Closing, feel free to reopen if anything doesn't work.

**Closed as completed by doronbehar** 2022-08-29 21:26 UTC
